events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log debug;

    sendfile on;
    server_tokens off;

    limit_req_zone $binary_remote_addr zone=ip:10m rate=10r/s;

    include /etc/nginx/conf.d/*.conf;
}