[build]
  command = "npm run build"
  publish = "out"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/"
  to = "/map/data/district"

[[redirects]]
  from = "/map"
  to = "/map/data/district"

[[redirects]]
  from = "/map/data"
  to = "/map/data/district"

[[redirects]]
  from = "/map/drm"
  to = "/map/drm/nta"
