[build]
  command = "npm run build"
  publish = "out"
  environment = { NODE_ENV="staging" }
  ignore = "false"

[[redirects]]
  from = "/"
  to = "/map/data/district"

[[redirects]]
  from = "/map"
  to = "/map/data/district"

[[redirects]]
  from = "/map/data"
  to = "/map/data/district"

[[redirects]]
  from = "/map/drm"
  to = "/map/drm/nta"

[[plugins]]
package = "@netlify/plugin-nextjs"
