[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/"
  to = "/map/data/district"

[[redirects]]
  from = "/map"
  to = "/map/data/district"

[[redirects]]
  from = "/map/data"
  to = "/map/data/district"

[[redirects]]
  from = "/map/drm"
  to = "/map/drm/nta"
