server {
    listen 80;
    server_name equitableexplorer.planning.nyc.gov;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /var/www/html;
    }

    location / {
        limit_req zone=ip burst=30 delay=15;
        limit_req_status 429;
        return 301 https://$host$request_uri;
    }
}

server {
    include /etc/nginx/bots.d/ddos.conf;
    include /etc/nginx/bots.d/blockbots.conf;

    listen 443 ssl;
    http2 on;

    server_name equitableexplorer.planning.nyc.gov;

    ssl_certificate /etc/nginx/certs/equitableexplorer-local.pem;
    ssl_certificate_key /etc/nginx/certs/equitableexplorer-local-key.pem;

    location / {
        include /etc/nginx/snippets/proxy-cache.conf;

        limit_req zone=ip burst=30 delay=15;
        limit_req_status 429;

        resolver 8.8.8.8 valid=300s;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_ssl_server_name on;
        proxy_ssl_name equity-tool.netlify.app;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host equity-tool.netlify.app;

        set $equity_tool_upstream https://equity-tool.netlify.app;
        proxy_pass $equity_tool_upstream;
    }
}

server {
    include /etc/nginx/bots.d/ddos.conf;
    include /etc/nginx/bots.d/blockbots.conf;

    listen 443 ssl;
    http2 on;

    server_name equitableexplorer.planninglabs.nyc;

    ssl_certificate /etc/nginx/certs/equitableexplorer-local.pem;
    ssl_certificate_key /etc/nginx/certs/equitableexplorer-local-key.pem;

    return 301 $scheme://equitableexplorer.planning.nyc.gov$request_uri;
}

server {
    listen 80;
    server_name staging-equitableexplorer.planninglabs.nyc;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /var/www/html;
    }

    location / {
        limit_req zone=ip burst=30 delay=15;
        limit_req_status 429;
        return 301 https://$host$request_uri;
    }
}

server {
    include /etc/nginx/bots.d/ddos.conf;
    include /etc/nginx/bots.d/blockbots.conf;

    listen 443 ssl;
    http2 on;

    server_name staging-equitableexplorer.planninglabs.nyc;

    ssl_certificate /etc/nginx/certs/equitableexplorer-local.pem;
    ssl_certificate_key /etc/nginx/certs/equitableexplorer-local-key.pem;

    location / {
    include /etc/nginx/snippets/proxy-cache.conf;

    limit_req zone=ip burst=30 delay=15;
    limit_req_status 429;

    proxy_http_version 1.1;
    proxy_set_header Connection "";

    proxy_ssl_server_name on;
    proxy_ssl_name equity-tool.netlify.app;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host equity-tool.netlify.app;

    proxy_pass https://equity-tool.netlify.app;
}
}